// <auto-generated />
namespace MedReviewer.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChangeMaxLengthOfReviewFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeMaxLengthOfReviewFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202003251443476_ChangeMaxLengthOfReviewFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
